### ISSUE TITLE
Please move this file to leetcode folder.

### ISSUE THREAD

**Issue by allworkdone** [ritikbanger/Hacktoberfest2022-DSA#140]
Please move this file to leetcode folder.

_Originally posted by @ritikbanger in https://github.com/ritikbanger/Hacktoberfest2022-DSA/pull/14#pullrequestreview-1127651296_
      
Sir completed your requested changes.
Please merge my request.

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me?
Thanks in advance :)

**Comment by allworkdone** [comment]
> Hello, Can you please assign this issue to me? Thanks in advance :)

Actually I have resolved this issue
